# Generated by Django 2.2.3 on 2019-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20190731_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotStoryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rnd_number', models.PositiveIntegerField(default=0)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
