# Generated by Django 2.2.3 on 2019-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_hotstorynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_date', models.DateTimeField(auto_now_add=True)),
                ('cronjob_comment', models.CharField(default='커뮤니티홈-오늘의 스토리 랜덤 숫자 동작 기록.', max_length=300)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
