# Generated by Django 2.2.3 on 2019-08-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_housewarming_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcontent',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
