# Generated by Django 2.2.3 on 2019-08-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20190805_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housewarming',
            old_name='author_profile',
            new_name='author_profile_image',
        ),
    ]
