# Generated by Django 2.2.3 on 2019-08-12 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20190805_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
