# Generated by Django 2.2.3 on 2019-08-12 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0036_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
