# Generated by Django 2.2.3 on 2019-08-16 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20190816_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
